name: Hello World Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Step
        run: echo "Hello, World!"
      - name: Step Two
        run: echo "This is another step in the workflow."
      - name: Display Date
        run: date
      - name: List Files
        run: ls -la
      - name: Show Current Directory
        run: pwd
      - name: whoami
        run: whoami
